// Generated by Wrangler by running `wrangler types`

interface Env {
	TIDB_CONNECTION_STRING: string;
	ADMIN_PASSWORD_HASH: "";
	ADMIN_PASSWORD: string;
	ENVIRONMENT: string;
	FORM_DO: DurableObjectNamespace<import("./src/worker/index").FormDO>;
	ASSETS: Fetcher;
}
