// Generated by Wrangler by running `wrangler types`

interface Env {
	ADMIN_PASSWORD_HASH: "";
	TIDB_CONNECTION_STRING: string;
	ADMIN_PASSWORD: string;
	ENVIRONMENT: string;
	FORM_DO: DurableObjectNamespace<import("./src/worker/index").FormDO>;
	IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
